#docker로 인한 root 권한 부여
sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  # manage.py 권한 부여
  - docker build -t test-django .
  - docker run -d -p 80:8000 test-django
  - docker ps -a

# command to install dependencies
# install: "pip install -r requirements.txt"

# command to run tests
# script:
#   - ./manage.py runserver 0:8000


# https://medium.com/mobileforgood/patterns-for-continuous-integration-with-docker-on-travis-ci-71857fff14c5



# before_install:
#   - npm install -g yarn
# before_deploy: # 배포하기전 하는 작업들
#   - rm -rf node_modules # travis가 설치한 node_moduels를 삭제
#   - zip -r node-koa-server * # node-koa-server 라는 이름으로 zip 파일 생성
#   - mkdir -p deploy # deploy 라는 디렉터리를 만듬
#   - mv node-koa-server.zip deploy/node-koa-server.zip # deploy 디렉터리로 node-koa-server.zip 파일을 이동
# deploy: # 배포
#   - provider: s3 # AWS S3를 의미
#     access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
#     secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
#     bucket: jeffchoi-ci-cd-tutorial # S3에 생성한 버킷
#     region: ap-northeast-2
#     skip_cleanup: true 
#     local_dir: deploy # deploy 디렉터리에 있는 파일을 s3로 업로드 하겠다는 의미
#     wait-until-deployed: true
#     on:
#       repo: jeffchoi72/node-koa-server #Github 주소
#       branch: master
#   - provider: codedeploy # AWS CodeDeploy를 의미
#     access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
#     secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
#     bucket: jeffchoi-ci-cd-tutorial # AWS CodeDeploy가 다운로드 받은 버킷
#     key: node-koa-server.zip # 해당 버킷에 저장되어 있는 파일 이름
#     bundle_type: zip # 버킷에 저장되어 있는 파일의 확장자
#     application: ci-cd-tutorial-code-deploy-service # AWS 배포 애플리케이션
#     deployment_group: ci-cd-deploy-grop # AWS 배포 애플리케이션에 만들어져 있는 배포 그룹
#     region: ap-northeast-2
#     wait-until-deployed: true
#     on:
#       repo: jeffchoi72/node-koa-server
#       branch: master
# https://velog.io/@jeff0720/Travis-CI-AWS-CodeDeploy-Docker-%EB%A1%9C-%EB%B0%B0%ED%8F%AC-%EC%9E%90%EB%8F%99%ED%99%94-%EB%B0%8F-%EB%AC%B4%EC%A4%91%EB%8B%A8-%EB%B0%B0%ED%8F%AC-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0-2#travis-ci-%EB%B0%B0%ED%8F%AC-%EC%84%A4%EC%A0%95